### ISSUE TITLE
Is it possible to enable as a global plugin?

### ISSUE THREAD

**Issue by philwills** [agemooij/sbt-prompt#5]
I'd rather not force my choice of prompt on all my co-workers, but haven't been able to get sbt-prompt working as a global plugin. I've got it so that I can inspect the promptTheme setting:

```
[status-app] $ inspect promptTheme
[info] Setting: com.scalapenos.sbt.prompt.PromptTheme = PromptTheme(List(Promptlet(<function1>), Promptlet(<function1>), Promptlet(<function1>), Promptlet(<function1>)),PromptletSeparator(<function2>))
[info] Description:
[info] 	A theme for rendering the SBT shell prompt.
[info] Provided by:
[info] 	{file:/Users/philip/status-app/}status-app/*:promptTheme
[info] Defined at:
[info] 	/Users/philip/.sbt/0.13/prompt.sbt:3
[info] Delegates:
[info] 	*:promptTheme
[info] 	{.}/*:promptTheme
[info] 	*/*:promptTheme
[info] Related:
[info] 	*/*:promptTheme
[status-app] $
```
but the prompt remains stubbornly boring.

**Comment by soc** [comment]
Just wasted a lot of time figuring that out ... would be great to add this to the README, I think the amount of people who want to add the config to an individual project might be negligible compared to those who want to add this as a global default that doesn't interfere with individual projects.

**Comment by agemooij** [comment]
@soc The README currently says the following:

> You will need to configure your terminal with a Powerline-patched font.

What would be a better way to say this?

**Comment by soc** [comment]
Hi @agemooij, no, my concern wasn't about that, but the lack of instructions on how to setup and configure this globally, the thing @fedesilva mentioned above.

**Comment by agemooij** [comment]
@soc Ah, I see. I'll add a section on that!

**Comment by agemooij** [comment]
@soc I have updated the README. Feel free to create a pull request if you think it should be documented differently or in a different location.

**Comment by soc** [comment]
@agemooij Cool, thanks a lot! This will help new users quite a bit! Looks good!
