### ISSUE TITLE
Automatically apply promptTheme to all subprojects

### ISSUE THREAD

**Issue by matanster** [agemooij/sbt-prompt#8]
Awesome sbt facelift. Would it make much sense automatically applying the a `promptTheme` setting to all subprojects of a multi-project build definition - for cleaner sbt files? I mean, typically you would expect the same theme all over, or wouldn't you?

**Comment by agemooij** [comment]
Hi and thanks!

It's pretty easy to make sbt-prompt available to all subprojects. You normally define some short of shared settings between all sub projects (like version, scalac settings, etc.). Just add the sbt-prompt settings to that list and you're good.

Another way to do this is to add sbt-pompt to your global SBT config in `~/.sbt/0.13/`. Then all projects have sbt-prompt by default.

Is this what you meant or did I misinterpret your question?

**Comment by matanster** [comment]
I guess you are right. [My project I tried your plugin for](https://github.com/CANVE/extractor) happens to comprise pretty versatile sub-projects (a compiler and sbt plugin included), so it shares little common settings between its subs, but above all if a global installation automatically applies to all sub-projects this is really not a concern. Thanks again for publishing this sbt power-up :)

**Comment by agemooij** [comment]
You're welcome. Feel free to let me known of any other difficulties you run into.

You're project looks interesting. I'll have a look at it.
