### ISSUE TITLE
Latest sbt-git

### ISSUE THREAD

**Issue by analytically** [agemooij/sbt-prompt#9]
Would be good if it'd use the latest sbt-git.

**Comment by agemooij** [comment]
Good point. I'll look into it!

**Comment by agemooij** [comment]
I just released version 1.0.0 of sbt-prompt, which features exactly zero new functionality; but it does have a modernized SBT build and a dependency on the latest version of sbt-git (0.8.5) 😄 

Try it out and let me know how it works!
